version: '3.8'

services:
  law_intern_flaskapp:
    build: .
    image: law_intern_flaskapp
    container_name: law_intern_flaskapp
    mem_limit: 1g
    ports:
      - "5050:5050"
    environment:
      pwrd: "${pwrd}"
      user: "${user}"
      genkey: "${genkey}"
      OPENAI_KEY: "${OPENAI_KEY}"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
    volumes:
      - /home/ec2-user/LawSchoolIntern/config:/app/config
    restart: unless-stopped

